### ISSUE TITLE
Terrarium in chapter 8 not printing correctly

### ISSUE THREAD

**Issue by zanqi** [marijnh/Eloquent-JavaScript-1st-edition#10]
terrarium.start() only outputs one line: [Object, Object]. No exception is displayed in the output.

Browser is the latest official version of Chrome: 28.0.1500.72 m

**Comment by marijnh** [comment]
Are you using the website's built-in console, or your browser's console? This still works fine for me.

**Comment by zanqi** [comment]
I was using the site's built-in console. Run codes by clicking the arrow button of the code snippet.

**Comment by marijnh** [comment]
Maybe you failed to run the code that defines the `toString` method on the terrarium? What happens when you shift-click the arrow next to the `terrarium.start` code?

**Comment by zanqi** [comment]
shift-click does print it correctly. I didn't know the shift-click shortcut. I must've missed running some code snippet.
