### ISSUE TITLE
How to make markdown version?

### ISSUE THREAD

**Issue by pcompassion** [marijnh/Eloquent-JavaScript-1st-edition#11]
I'm trying to make markdown version out of it.. 
If it's doable, can someone provide a pointer to where to start?

**Comment by marijnh** [comment]
You might be able to run a bunch of regexps over book.txt. Why, though?

As an aside, I'm in the process of writing a second edition in AsciiDoc.

**Comment by pcompassion** [comment]
Thanks for the fast response.

I thought I might translate it to Korean and thought markdown would be convenient.  
Glad to hear 2nd edition is coming out, would it be under a similar creative commons license? (So that I can translate it)

When do you think it would come out?

Thank you!

**Comment by marijnh** [comment]
Are you Jang Seunghun, by any chance? Or another person working on a Korean translation?

The second edition will also be under a CC license (though the non-commercial variant this time). It's hard to say when it will be finished. With luck, end of the year. Maybe a few months after that.

**Comment by pcompassion** [comment]
No I'm not Jang Seunghun. 

I've been translating tutorials for a month and publishing it at codeflow.co.kr which just went live.  
And I thought eloquent javascript would be a great fit.  

I'll keep an eye on your second version, hope it goes smooth as planned.

**Comment by marijnh** [comment]
Jang did some work translating the current edition to Korean, but I haven't heard from him in a while.

Closing this for now.

**Comment by pcompassion** [comment]
Let me know if you need a Korean translator. I can even start working on it before it comes out :+1:
