### ISSUE TITLE
Mention existence in ECMA 5 of some of the utilities defined in the book

### ISSUE THREAD

**Issue by marijnh** [marijnh/Eloquent-JavaScript-1st-edition#2]
When talking about forEach, map, reduce, clone, etc, there should be a note that these are built-in in ECMAScript 5. Also, the introduction should say a bit more about this.

**Comment by fauzana** [comment]
I think built-in in ECMAScript functions are no longer an introductory issue today.

**Comment by marijnh** [comment]
Also this edition hasn't been current in many years.
