### ISSUE TITLE
Filenames and page names are not distinct and therefor not easy to translate

### ISSUE THREAD

**Issue by pandark** [marijnh/Eloquent-JavaScript-1st-edition#4]
Hi,

I translated the renderer source in French but I faced an issue.
I have used a hack in bash to get around the problem since I don't really know haskell.

I'd like the links to be like this: &lt;a href="chapter1.html"&gt;chapitre 1&lt;/a&gt;.
My problem is that the filename (chapter1.html, for example) and the page name (chapter 1 in English, or chapitre 1 in French) are too strongly tightened so can't do that without modifying the actual code.

++
Pandark

**Comment by marijnh** [comment]
So modify the code. Changing strings is unlikely to break it.

**Comment by pandark** [comment]
As I said, I try to keep the same filenames, and if I change the string [here](https://github.com/marijnh/Eloquent-JavaScript/blob/master/renderer/Main.hs#L302), I think it will not only change the html text, but also the filenames…

**Comment by marijnh** [comment]
Ah, I see. But why do you want to keep the filenames? Anyway, you can split the function used to make the filename from the one used elsewhere, something like this:

```

diff --git a/renderer/Main.hs b/renderer/Main.hs
index 8ca3696..64e7e15 100644
--- a/renderer/Main.hs
+++ b/renderer/Main.hs
@@ -301,7 +301,10 @@ findExercise chapters tag = info
 typeName c = case (ctype c)
              of Normal -> "chapter"
                 Appendix -> "appendix"
-fileName c = (typeName c) ++ (show (num c)) ++ ".html"
+fileTypeName c = case (ctype c)
+                 of Normal -> "chapter"
+                    Appendix -> "appendix"
+fileName c = (fileTypeName c) ++ (show (num c)) ++ ".html"

 outputPath = "web/"
 imgPath = "img/"
```

**Comment by pandark** [comment]
Thank you, that works perfectly.
